# Generated by Django 4.2.11 on 2024-04-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='room',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phonebook.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phonebook.subscriber'),
        ),
    ]
