# Generated by Django 4.2.11 on 2024-04-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_remove_phone_room_subscriber_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='phonebook.phone'),
            preserve_default=False,
        ),
    ]
